import { defineStore } from 'pinia'
import { ref } from 'vue'

export const plantsStore = defineStore('plantTypes', () => {
    const plantTypes = ref([
        {
            type: 'Grass',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 0,
            maxWater: 2,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 1,
            fertilizerRequired: 1,
            yield: 1,
            seedCost: 2,
            seedlingCost: 5,
            basePrice: 1, shelfLife: 10,
            icon: '🌱'
        },
        {
            type: 'Corn',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Summer',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 3,
            seedCost: 3,
            seedlingCost: 8,
            basePrice: 1, shelfLife: 15,
            icon: '🌽'
        },
        {
            type: 'Tomato',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Summer',
            minWater: 1,
            maxWater: 3,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 2,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 4,
            seedlingCost: 10,
            basePrice: 1, shelfLife: 7,
            icon: '🍅'
        },
        {
            type: 'Lettuce',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 2,
            minFertility: 1,
            maxFertility: 2,
            waterRequired: 2,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 2,
            seedlingCost: 7,
            basePrice: 1, shelfLife: 6,
            icon: '🥬'
        },
        {
            type: 'Carrot',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Autumn',
            minWater: 1,
            maxWater: 2,
            minFertility: 1,
            maxFertility: 2,
            waterRequired: 1,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 2,
            seedlingCost: 6,
            basePrice: 1, shelfLife: 20,
            icon: '🥕'
        },
        {
            type: 'Coffee',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Summer',
            minWater: 2,
            maxWater: 3,
            minFertility: 2,
            maxFertility: 3,
            waterRequired: 3,
            fertilizerRequired: 2,
            yield: 2,
            seedCost: 6,
            seedlingCost: 14,
            basePrice: 2, shelfLife: 30,
            icon: '☕'
        },
        {
            type: 'Pumpkin',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Overripe', 'Rotten'],
            preferredSeason: 'Autumn',
            minWater: 2,
            maxWater: 4,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 3,
            fertilizerRequired: 2,
            yield: 4,
            seedCost: 4,
            seedlingCost: 12,
            basePrice: 2, shelfLife: 40,
            icon: '🎃'
        },
        // NEW PLANTS BELOW
        {
            type: 'Apple Tree',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Young Tree', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 5,
            seedCost: 0,
            seedlingCost: 15,
            basePrice: 3, shelfLife: 20,
            icon: '🍏'
        },
        {
            type: 'Pear Tree',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Young Tree', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 5,
            seedCost: 0,
            seedlingCost: 15,
            basePrice: 3, shelfLife: 20,
            icon: '🍐'
        },
        {
            type: 'Almond Tree',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Young Tree', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 4,
            seedCost: 0,
            seedlingCost: 20,
            basePrice: 5, shelfLife: 25,
            icon: '🌰'
        },
        {
            type: 'Lavender',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Blooming', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 0,
            maxWater: 2,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 1,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 3,
            seedlingCost: 8,
            basePrice: 3, shelfLife: 15,
            icon: '💜'
        },
        {
            type: 'Clover',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Flowering', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 0,
            maxWater: 2,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 1,
            fertilizerRequired: 0,
            yield: 1,
            seedCost: 2,
            seedlingCost: 5,
            basePrice: 1, shelfLife: 10,
            icon: '☘️'
        },
        {
            type: 'Sunflower',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Flowering', 'Overripe', 'Rotten'],
            preferredSeason: 'Summer',
            minWater: 1,
            maxWater: 3,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 1,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 3,
            seedlingCost: 8,
            basePrice: 2, shelfLife: 18,
            icon: '🌻'
        },
        {
            type: 'Oak Tree',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Sapling', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Autumn',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 6,
            seedCost: 0,
            seedlingCost: 25,
            basePrice: 8, shelfLife: 60,
            icon: '🌳'
        },
        {
            type: 'Poplar',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Sapling', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Autumn',
            minWater: 1,
            maxWater: 3,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 2,
            fertilizerRequired: 2,
            yield: 5,
            seedCost: 0,
            seedlingCost: 18,
            basePrice: 7, shelfLife: 55,
            icon: '🌲'
        },
        {
            type: 'Willow',
            plantingOptions: ['Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Sapling', 'Mature', 'Harvestable', 'Old'],
            preferredSeason: 'Autumn',
            minWater: 2,
            maxWater: 4,
            minFertility: 1,
            maxFertility: 3,
            waterRequired: 3,
            fertilizerRequired: 2,
            yield: 4,
            seedCost: 0,
            seedlingCost: 16,
            basePrice: 6, shelfLife: 40,
            icon: '🌳'
        },
        {
            type: 'Strawberry',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Flowering', 'Harvestable', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 2,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 2,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 3,
            seedlingCost: 9,
            basePrice: 3, shelfLife: 8,
            icon: '🍓'
        },
        {
            type: 'Blueberry',
            plantingOptions: ['Seed', 'Seedling'],
            growthStages: ['Seed', 'Seedling', 'Growing', 'Mature', 'Flowering', 'Harvestable', 'Overripe', 'Rotten'],
            preferredSeason: 'Spring',
            minWater: 1,
            maxWater: 2,
            minFertility: 0,
            maxFertility: 2,
            waterRequired: 2,
            fertilizerRequired: 1,
            yield: 2,
            seedCost: 3,
            seedlingCost: 9,
            basePrice: 4, shelfLife: 8,
            icon: '🫐'
        }
    ])


    return { plantTypes }
})
